#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# コミットメッセージの形式をチェック
message="$(cat $1)"
requiredPattern="^(文書|設定|機能|修正|リファクタ|テスト|スタイル|依存関係|ビルド|その他): .+"
if ! [[ $message =~ $requiredPattern ]]; then
  echo "🛑 コミットメッセージの形式が不正です。"
  echo "以下の接頭辞のいずれかを使用してください:"
  echo "文書、設定、機能、修正、リファクタ、テスト、スタイル、依存関係、ビルド、その他"
  echo "例: 「機能: ログイン機能を実装」"
  exit 1
fi 