name: Database Migration

on:
  push:
    branches:
      - main
      - development
      - 'release/*'
    # paths: # Temporarily commented out to force execution
    #   - 'infrastructure/database/migrations/**'
    #   - '.github/workflows/database-migration.yml'

jobs:
  migrate-database:
    name: Database Migration
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'Production') || (startsWith(github.ref, 'refs/heads/release/') && 'staging') || 'Preview' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Use Node.js v22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # - name: Install PostgreSQL client # Removed, node-pg-migrate handles connection
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y postgresql-client

      - name: Apply database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # node-pg-migrate uses DATABASE_URL or standard PG* env vars
        run: npm run db:migrate # Use the npm script defined in package.json
